services:
  web:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/app
      - chroma_data:/app/chroma_db
    environment:
      - FLASK_ENV=development
      - PYTHONPATH=/app
    command: >
      sh -c "flask run --host=0.0.0.0 --port=5000 --reload"

  prod:
    build: .
    ports:
      - "8000:5000"
    environment:
      - FLASK_ENV=production
    command: gunicorn -w 4 -b 0.0.0.0:5000 app:app

  test:
    build: .
    volumes:
      - .:/app
    command: pytest -n auto

volumes:
  chroma_data:
